name: Cron Job
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch: # Добавляем возможность ручного запуска
jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - name: Call API endpoint
        id: api_call
        run: |
          echo "Starting API call..."
          RESPONSE=$(curl -L -X POST 'https://digital-birthday-reminder.vercel.app/api/send-notifications' \
          -H 'Content-Type: application/json')
          echo "API Response: $RESPONSE"
          
          # Check if the call was successful
          if [ $? -eq 0 ]; then
            echo "API call successful"
          else
            echo "API call failed"
            exit 1
          fi
