name: Birthday Notifications
on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - name: Check environment variables
        run: |
          if [ -z "$NEXT_PUBLIC_SUPABASE_URL" ]; then
            echo "Error: NEXT_PUBLIC_SUPABASE_URL is not set"
            exit 1
          fi
          if [ -z "$SUPABASE_SERVICE_ROLE_KEY" ]; then
            echo "Error: SUPABASE_SERVICE_ROLE_KEY is not set"
            exit 1
          fi

      - name: Send birthday notifications
        id: send_notifications
        run: |
          echo "Checking for birthdays today..."
          
          # Determine trigger type
          TRIGGER_TYPE="workflow_dispatch"
          
          # Form URL based on trigger type
          if [ "$TRIGGER_TYPE" = "workflow_dispatch" ]; then
            echo "Manual trigger detected - sending notifications if there are birthdays today"
            API_URL='https://digital-birthday-reminder.vercel.app/api/send-notifications?force=true'
          else
            echo "Scheduled trigger detected - running normal check"
            API_URL='https://digital-birthday-reminder.vercel.app/api/send-notifications'
          fi
          
          # Send request with authentication headers
          RESPONSE=$(curl -L -X POST "$API_URL" \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
          -H "x-supabase-url: $NEXT_PUBLIC_SUPABASE_URL" \
          -v)
          
          echo "API Response: $RESPONSE"
          
          if echo "$RESPONSE" | grep -q '"error":'; then
            echo "API returned an error"
            exit 1
          fi
          
          if echo "$RESPONSE" | grep -q '"success":true'; then
            if echo "$RESPONSE" | grep -q '"No birthdays today"'; then
              echo "No birthdays found for today"
            else
              echo "Birthday notifications sent successfully"
            fi
          else
            echo "API call failed"
            exit 1
          fi
