name: Cron Job
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch: # Добавляем возможность ручного запуска
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API endpoint
        id: api_call
        run: |
          echo "Starting API call..."
          RESPONSE=$(curl -L -X POST 'https://abzpkoyyxxkduvovsmvx.supabase.co/functions/v1/birthday-notifications-cron' \
          -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFienBrb3l5eHhrZHV2b3ZzbXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NDQ1NTgsImV4cCI6MjA1NzAyMDU1OH0.__Ij4qZtF2nr_8pT1PMNDFEyUAKUT5ikhCFkxud_u2Q' \
          -H 'Content-Type: application/json' \
          --data '{"name":"Functions"}')
          echo "API Response: $RESPONSE"
          
          # Check if the call was successful
          if [ $? -eq 0 ]; then
            echo "API call successful"
          else
            echo "API call failed"
            exit 1
          fi
