name: Birthday Notifications
on:
  schedule:
    - cron: '0 0,6,12,18 * * *'  # Запуск в 00:00, 06:00, 12:00 и 18:00 UTC
  workflow_dispatch: # Возможность ручного запуска

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - name: Check environment variables
        run: |
          if [ -z "$NEXT_PUBLIC_SUPABASE_URL" ]; then
            echo "Error: NEXT_PUBLIC_SUPABASE_URL is not set"
            exit 1
          fi
          if [ -z "$SUPABASE_SERVICE_ROLE_KEY" ]; then
            echo "Error: SUPABASE_SERVICE_ROLE_KEY is not set"
            exit 1
          fi

      - name: Send birthday notifications
        id: send_notifications
        run: |
          echo "Checking for birthdays today..."
          
          # Определяем тип запуска (manual или scheduled)
          TRIGGER_TYPE="${{ github.event_name }}"
          
          # Формируем URL в зависимости от типа запуска
          if [ "$TRIGGER_TYPE" = "workflow_dispatch" ]; then
            echo "Manual trigger detected - sending notifications if there are birthdays today"
            API_URL='https://digital-birthday-reminder.vercel.app/api/send-notifications?force=true'
          else
            echo "Scheduled trigger detected - running normal check"
            API_URL='https://digital-birthday-reminder.vercel.app/api/send-notifications'
          fi
          
          # Отправляем запрос
          RESPONSE=$(curl -L -X POST "$API_URL" \
          -H 'Content-Type: application/json' \
          -v)
          
          echo "API Response: $RESPONSE"
          
          # Проверяем наличие ошибки в ответе
          if echo "$RESPONSE" | grep -q '"error":'; then
            echo "API returned an error"
            exit 1
          fi
          
          # Проверяем успешность выполнения
          if echo "$RESPONSE" | grep -q '"success":true'; then
            if echo "$RESPONSE" | grep -q '"No birthdays today"'; then
              echo "No birthdays found for today"
            else
              echo "Birthday notifications sent successfully"
            fi
          else
            echo "API call failed"
            exit 1
          fi
