name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 1 * *' # Раз в месяц (1-го числа каждого месяца)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Keepalive Action
        uses: gautamkrishnar/keepalive-workflow@v2
